{
 "title": "Game Service Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "go_memory_used_bytes", "legendFormat": "{{go_memory_type}}" }
   ]
  },
  {
   "title": "Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, \n  rate(http_server_request_duration_seconds_bucket[5m])\n)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, \n  rate(http_server_request_duration_seconds_bucket[5m])\n)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, \n  rate(http_server_request_duration_seconds_bucket[5m])\n)",
     "legendFormat": "P99"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{http_status_code=~\"5..\"}[5m])) \n/ \nsum(rate(http_server_request_duration_seconds_count[5m])) * 100",
     "legendFormat": "Error Rate"
    }
   ]
  },
  {
   "title": "Request time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_server_request_duration_seconds_sum[5m]) \n/ \nrate(http_server_request_duration_seconds_count[5m])",
     "legendFormat": "Average duration"
    }
   ]
  },
  {
   "title": "Request Rate (QPS)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(http_server_request_duration_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate by methods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (http_request_method) (\n  rate(http_server_request_duration_seconds_count[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate by status code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (http_response_status_code) (\n  rate(http_server_request_duration_seconds_count[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dice game",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true
  },
  {
   "title": "Total Dice Rolls",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dice_rolls_total" }
   ]
  },
  {
   "title": "Dice Roll Rate (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    { "expr": "rate(dice_rolls_total[1m])", "legendFormat": "Rolls/sec" }
   ]
  }
 ]
}